### ISSUE TITLE
 fatal error LNK1104: cannot open file 'utils.lib'

### ISSUE THREAD

**Issue by MichaelDohmenDUE** [JensDerKrueger/CG#1]
Hello,

I am getting an issue when i try to build one of the later exercieses except for the first one.

When I build the exercise, I get the following error:

C:\Users\micha\Source\Repos\CG\03_Splines\VS\LINK : fatal error LNK1104: cannot open file 'utils.lib'

When I looked at the folder structure it becomes quickly apparent that a file is just missing. 

<img width="863" alt="2024-05-17 22_24_33-Clipboard" src="https://github.com/JensDerKrueger/CG/assets/104837391/7ff334cd-d992-4695-944e-e25bcff3f0ed">

Manually adding the file Utils.lib to the coresponding exercise fixes the issue for me and I can build normally.

I am sure this is not the intended way of building the exercise, maybe I am doing something wrong?

Kind Regards

Michael

**Comment by JensDerKrueger** [comment]
I'm not sure how you opened the project for assignment 3 but if you simply open the solution int the VS folder it works fine. I just tested it with the latest VS. Just make sure you hit ok when VS asks you to upgrade the project to your VS version.
